#!/usr/bin/env bun
/**
 * Reflex Setup Wizard - Interactive onboarding for beginners
 * 
 * Asks questions, detects project type, creates config, offers to run first scan
 */

import { parseArgs } from "node:util";
import * as readline from "node:readline";
import * as fs from "node:fs";
import * as path from "node:path";

const { values } = parseArgs({
  options: {
    project: { type: "string", short: "p" },
    quick: { type: "boolean", default: false },
    help: { type: "boolean", short: "h", default: false },
  },
  strict: false,
});

if (values.help) {
  console.log(`
Reflex Setup Wizard - Interactive onboarding for beginners

Usage:
  bun wizard.ts [options]

Options:
  -p, --project <dir>   Project directory to set up
  --quick                Skip interactive prompts, use defaults
  -h, --help             Show this help

The wizard will:
  1. Ask about your project
  2. Create .reflex.yml config
  3. Offer to run first quality check
`);
  process.exit(0);
}

interface ProjectConfig {
  name: string;
  type: string;
  language: string;
  llmProvider: string;
  autoFix: boolean;
  notifications: {
    slack?: string;
    discord?: string;
    telegram?: string;
  };
}

async function runWizard(): Promise<void> {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  const question = (prompt: string): Promise<string> => 
    new Promise(resolve => rl.question(prompt, resolve));

  console.log("\n⚡ REFLEX SETUP WIZARD\n");
  console.log("Let's get your project set up. I'll ask a few questions.\n");

  const config: ProjectConfig = {
    name: "",
    type: "",
    language: "",
    llmProvider: "",
    autoFix: false,
    notifications: {},
  };

  // Detect project
  const projectPath = (values.project as string) || process.cwd();
  config.name = path.basename(projectPath);

  // Detect language
  if (fs.existsSync(path.join(projectPath, "tsconfig.json"))) {
    config.language = "typescript";
  } else if (fs.existsSync(path.join(projectPath, "package.json"))) {
    config.language = "javascript";
  } else if (fs.existsSync(path.join(projectPath, "pyproject.toml"))) {
    config.language = "python";
  } else {
    config.language = await question("What language is this project? (typescript/javascript/python) ") || "typescript";
  }

  console.log(`\nDetected: ${config.language} project\n`);

  // Project type
  if (values.quick) {
    config.type = "web";
    config.llmProvider = "zo";
    config.autoFix = true;
  } else {
    config.type = await question("Project type? (web/api/cli/library) ") || "web";
    config.llmProvider = await question("LLM provider? (zo/openai/anthropic/ollama) [default: zo] ") || "zo";
    const autoFixAnswer = await question("Enable auto-fix for safe playbooks? (y/n) [default: y] ");
    config.autoFix = autoFixAnswer.toLowerCase() !== "n";
  }

  rl.close();

  // Generate config file
  const configContent = generateConfig(config);
  const configPath = path.join(projectPath, ".reflex.yml");
  
  fs.writeFileSync(configPath, configContent);
  console.log(`\n✓ Created .reflex.yml\n`);

  // Offer to run first scan
  console.log("=== CONFIGURATION COMPLETE ===\n");
  console.log(`Project: ${config.name}`);
  console.log(`Language: ${config.language}`);
  console.log(`Type: ${config.type}`);
  console.log(`LLM: ${config.llmProvider}`);
  console.log(`Auto-fix: ${config.autoFix ? "enabled" : "disabled"}`);
  console.log(`\nConfig saved to: ${configPath}`);
  console.log("\nNext step: Run `reflex check` to see your quality score.\n");
}

function generateConfig(config: ProjectConfig): string {
  return `# Reflex Configuration
# Generated by setup wizard

project:
  name: ${config.name}
  type: ${config.type}
  language: ${config.language}

# LLM Provider for autonomous fixes
llm:
  provider: ${config.llmProvider}
  # model: gpt-5.4  # Uncomment to override

# Quality thresholds (0-100)
thresholds:
  typeIntegrity: 95
  testCoverage: 85
  codeComplexity: 80
  security: 100

# Safety settings
safety:
  autoApproveSafe: ${config.autoFix}
  maxFilesPerCycle: 5
  requireApproval:
    - typeElimination
    - criticalPathCoverage
    - interfaceExtraction

# Notifications (uncomment to enable)
# notifications:
#   slack: \${REFLEX_SLACK_WEBHOOK}
#   discord: \${REFLEX_DISCORD_WEBHOOK}
#   telegram:
#     botToken: \${REFLEX_TELEGRAM_BOT_TOKEN}
#     chatId: \${REFLEX_TELEGRAM_CHAT_ID}
`;
}

runWizard().catch(console.error);